name: CI/CD Deploy Frontend to AWS ECS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Build, Push and Deploy to ECS Fargate
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código fuente del repositorio
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Configurar las credenciales de AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Autenticarse en Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Compilar la imagen inyectando la URL del Balanceador de AWS y subirla a ECR
      - name: Build, Tag, and Push Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innovatech-frontend
          IMAGE_TAG: ${{ github.sha }}
          # REEMPLAZA ESTA URL por la DNS real de tu Application Load Balancer cuando AWS te la entregue
          ALB_DNS_URL: "http://innovatech-alb-123456789.us-east-1.elb.amazonaws.com:3000"
        run: |
          # Construimos pasando la URL de la API como un argumento de compilación (--build-arg)
          docker build \
            --build-arg VITE_API_URL=$ALB_DNS_URL \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
          # Subir la imagen etiquetada al repositorio privado de ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # 5. Forzar el redespliegue en el servicio de ECS Fargate
      - name: Force ECS Service Deployment
        run: |
          aws ecs update-service \
            --cluster innovatech-cluster \
            --service innovatech-frontend-service \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
